const initial={projects:[{name:'Bloom Studio website',client:'Nila Rao',progress:82,status:'In delivery'},{name:'Atlas onboarding',client:'Atlas Ventures',progress:58,status:'In delivery'},{name:'Arjun brand refresh',client:'Arjun Mehta',progress:15,status:'Proposal sent'},{name:'Northstar dashboard',client:'Northstar Labs',progress:36,status:'In progress'}],tasks:[{id:1,text:'Send Bloom Studio milestone invoice',due:'Today',done:false},{id:2,text:'Review Atlas scope change',due:'Today',done:false},{id:3,text:'Send Arjun a proposal follow-up',due:'Today',done:false},{id:4,text:'Prepare Northstar weekly update',due:'Tomorrow',done:false}],drafts:[]};
const SUPABASE_URL='https://hnxaylouonbvzfhqbyuv.supabase.co';
const SUPABASE_KEY='sb_publishable_eb7hMTl7YyGOCdSjyHa_FQ_LJFhguUc';
const dbHeaders={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',Prefer:'return=representation'};
let state=JSON.parse(localStorage.getItem('clientops-state')||JSON.stringify(initial)); state.drafts ||= [];
const $=s=>document.querySelector(s); const persist=()=>{localStorage.setItem('clientops-state',JSON.stringify(state)); syncRemote();};
let syncTimer; function syncRemote(){clearTimeout(syncTimer);syncTimer=setTimeout(async()=>{try{await fetch(`${SUPABASE_URL}/rest/v1/tasks`,{method:'POST',headers:{...dbHeaders,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(state.tasks.map(t=>({id:Number(t.id),text:t.text,due:t.due,done:t.done})))});if(state.drafts.length) await fetch(`${SUPABASE_URL}/rest/v1/drafts`,{method:'POST',headers:{...dbHeaders,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(state.drafts)});}catch(e){console.warn('Remote sync unavailable; local mode remains active',e)}},250)}
async function loadRemote(){try{const h={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`};const [tasks,drafts]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/tasks?select=*&order=created_at.asc`,{headers:h}),fetch(`${SUPABASE_URL}/rest/v1/drafts?select=*&order=created_at.asc`,{headers:h})]);if(tasks.ok){const rows=await tasks.json();if(rows.length)state.tasks=rows.map(t=>({id:t.id,text:t.text,due:t.due,done:t.done}));}if(drafts.ok)state.drafts=await drafts.json();localStorage.setItem('clientops-state',JSON.stringify(state));render();}catch(e){console.warn('Using local demo data',e)}}
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){ $('#projectList').innerHTML=state.projects.map(p=>`<div class="project"><div class="project-top"><strong>${escapeHTML(p.name)}</strong><span class="status">${escapeHTML(p.status)}</span></div><div class="project-client">${escapeHTML(p.client)} · ${p.progress}% complete</div><div class="bar"><i style="width:${Math.max(0,Math.min(100,Number(p.progress)||0))}%"></i></div></div>`).join('');$('#taskList').innerHTML=state.tasks.map(t=>`<div class="task"><input type="checkbox" data-id="${Number(t.id)}" ${t.done?'checked':''} aria-label="Complete ${escapeHTML(t.text)}"><label class="${t.done?'done':''}">${escapeHTML(t.text)}</label><small>${escapeHTML(t.due)}</small></div>`).join('');let done=state.tasks.filter(t=>t.done).length;$('#completionLabel').textContent=`${done} of ${state.tasks.length} complete`;$('#projectCount').textContent=state.projects.length;$('#followupCount').textContent=state.tasks.filter(t=>!t.done&&t.text.toLowerCase().includes('follow')).length||'0';persist()}
function result(message,data={}){render();return {content:[{type:'text',text:message}],structuredContent:data};}
async function registerWebMCP(){const mc=document.modelContext||navigator.modelContext;if(!mc?.registerTool){$('#mcpStatus').textContent='WebMCP: open in ChatGPT or Chrome testing mode';return;}const tools=[
 ['get_workspace_brief','Get a concise, read-only briefing of active client work, cash at risk, and tasks due today.',{type:'object',properties:{}},()=>{const dueToday=state.tasks.filter(t=>!t.done&&t.due.toLowerCase()==='today');return result(`ClientOps briefing: ${state.projects.length} active projects. ₹68,500 outstanding. ${dueToday.length?`${dueToday.length} task${dueToday.length===1?'':'s'} due today: ${dueToday.map(t=>t.text).join('; ')}.`:'No tasks are due today.'}`,{projects:state.projects,tasks:state.tasks,dueToday,outstanding:{amount:68500,currency:'INR'}})}],
 ['create_work_item','Create a non-financial work item in the shared ClientOps queue.',{type:'object',properties:{title:{type:'string',description:'Clear task title'},due:{type:'string',description:'Due date label, e.g. Today or Friday'}},required:['title']},i=>{const task={id:Date.now(),text:i.title.trim(),due:i.due||'Unscheduled',done:false};state.tasks.unshift(task);return result(`Created work item: ${task.text}.`,{task});}],
 ['draft_follow_up','Create a reviewable follow-up draft for a client. This tool never sends messages.',{type:'object',properties:{client:{type:'string'},context:{type:'string'}},required:['client']},i=>{const draft={id:Date.now(),type:'follow_up',client:i.client,context:i.context||'the proposal',created_at:new Date().toISOString()};state.drafts.push(draft);return result(`Draft ready for ${i.client}: “Hi ${i.client}, just checking in on ${draft.context}. I can reserve a delivery slot this week if you'd like to move ahead.” It has not been sent.`,{status:'draft_created',...draft,requires_human_approval:true})}],
 ['create_invoice_draft','Create a reviewable invoice draft for a completed project milestone. This tool never charges or sends an invoice.',{type:'object',properties:{project:{type:'string'},amount:{type:'number'},currency:{type:'string'}},required:['project','amount']},i=>{const draft={id:Date.now(),type:'invoice',project:i.project,amount:i.amount,currency:i.currency||'INR',created_at:new Date().toISOString()};state.drafts.push(draft);return result(`Invoice draft created for ${i.project}: ${draft.currency} ${draft.amount}. It requires human review and approval before sending.`,{status:'draft_created',...draft,requires_human_approval:true})}],
 ['update_task_status','Mark a ClientOps work item complete or incomplete.',{type:'object',properties:{task_id:{type:'number'},complete:{type:'boolean'}},required:['task_id','complete']},i=>{const t=state.tasks.find(x=>x.id===i.task_id);if(!t) return result('No matching work item was found.',{error:'not_found'});t.done=i.complete;return result(`${t.text} marked ${i.complete?'complete':'incomplete'}.`,{task:t});}]
 ];try{for(const [name,description,inputSchema,execute] of tools){await mc.registerTool({name,description,inputSchema,annotations:{readOnlyHint:name==='get_workspace_brief'},execute});}$('#mcpStatus').textContent=`WebMCP: ${tools.length} tools registered ✓`;}catch(error){console.error('WebMCP registration failed',error);$('#mcpStatus').textContent='WebMCP: registration unavailable';}}
document.addEventListener('change',e=>{if(e.target.matches('.task input')){let t=state.tasks.find(t=>t.id===Number(e.target.dataset.id));if(t){t.done=e.target.checked;render();}}});$('#seedButton').onclick=()=>{state=JSON.parse(JSON.stringify(initial));render()};$('#newTaskButton').onclick=()=>{let title=prompt('What needs doing?');if(title?.trim()){state.tasks.unshift({id:Date.now(),text:title.trim(),due:'Unscheduled',done:false});render()}};$('#showProjects').onclick=()=>{$('#dialogContent').innerHTML=`<h3>All projects</h3>${state.projects.map(p=>`<p><strong>${escapeHTML(p.name)}</strong><br><small>${escapeHTML(p.client)} · ${p.progress}% · ${escapeHTML(p.status)}</small></p>`).join('')}`;$('#actionDialog').showModal()};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{let action=b.dataset.action;let copy={invoice:['Invoice draft','Bloom Studio · Milestone 2 · ₹32,500','This is a draft only. Review it before it is sent.'],followup:['Follow-up draft','Arjun Mehta · Proposal follow-up','Hi Arjun, just checking whether you had a chance to review the proposal. I have availability to start next week.'],scope:['Scope review','Atlas onboarding · 2 new requests','The agent flagged approximately 6 hours of unscheduled work. Create a change request before accepting it.']}[action];$('#dialogContent').innerHTML=`<h3>${copy[0]}</h3><p><strong>${copy[1]}</strong></p><p>${copy[2]}</p>`;$('#actionDialog').showModal()});render();registerWebMCP();loadRemote();
